Policy management feature
Venafi/terraform-provider-venafi pull request #53
Opened 2021-05-13 22:01 UTC by angelmoo

now using terreform-provider-venafi, user can create on VaaS or TPP and can import a policy from VaaS or TPP
and also test cases for creating and importing policies were implemented.

2021-05-13 22:24 UTC, marcos-albornoz approved these changes

2021-05-13 22:29 UTC, rvelaVenafi requested changes

2021-05-13 22:29 UTC, rvelaVenafi commented on .gitignore
> +terraform.d
No new line at end of file

2021-05-13 22:29 UTC, rvelaVenafi commented on test_files/empty_policy.json
> +}
No new line at end of file

2021-05-13 22:29 UTC, rvelaVenafi commented on test_files/policy_specification_cloud.json
> +}
No new line at end of file

2021-05-13 22:29 UTC, rvelaVenafi commented on test_files/policy_specification_tpp.json
> +}
No new line at end of file

2021-05-13 22:29 UTC, rvelaVenafi commented on test_files/policy_specification_tpp_management.json
> +}
No new line at end of file

2021-05-24 22:20 UTC, angelmoo commented on .gitignore
> +terraform.d
fixed on the most recent commit

2021-05-24 22:20 UTC, angelmoo commented on test_files/empty_policy.json
> +}
fixed on the most recent commit

2021-05-24 22:20 UTC, angelmoo commented on test_files/policy_specification_tpp.json
> +}
fixed on the most recent commit

2021-05-24 22:20 UTC, angelmoo commented on test_files/policy_specification_tpp_management.json
> +}
fixed on the most recent commit

2021-05-24 22:21 UTC, angelmoo commented on test_files/policy_specification_cloud.json
> +}
fixed on the most recent commit

2021-05-24 22:31 UTC, marcos-albornoz approved these changes

2021-05-27 18:11 UTC, tr1ck3r approved these changes

2021-05-27 20:23 UTC, rvelaVenafi approved these changes

2021-05-27 20:30 UTC, merged